{{- $namespace := .Values.namespace -}}
{{- $secretName := .Values.storage.secretName -}}
{{- $env := .Values.env -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "psdbs.fullname" . }}-manager-secret
  namespace: {{ $namespace }}
data:
{{ include  "psdbs.secret" .}}
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}

data:
  azurestorageaccountkey: {{ default "" .Values.storage.azurestorageaccountkey}}
  azurestorageaccountname: {{ default "" .Values.storage.azurestorageaccountname}}
type: Opaque
---

kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "psdbs.fullname" . }}-ms-secret"
  namespace: {{ $namespace }}
data:
  {{ include  "psdbs.ms.secret" .}}
type: Opaque
